# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cop_gpt',
                'doc_host': 'https://jean-kunz.github.io',
                'git_url': 'https://github.com/jean-kunz/cop_gpt',
                'lib_path': 'cop_gpt'},
  'syms': {'cop_gpt.mingpt': {}}}