# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/mingpt.ipynb.

# %% auto 0
__all__ = ['device']

# %% ../nbs/mingpt.ipynb 2
import torch
import torch.nn as nn
from torch.nn import functional as F
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# %% ../nbs/mingpt.ipynb 3
device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")
device
